// Generated by figma Go Grafcet.Online Plugin
// https://www.figma.com/file/7mzIAnqqgMZSFiliyLle1U/getChildIndex-%40Go-Plugin-Opensource%2FFigma-Utilities?node-id=2%3A2

function getChildIndex(child: SceneNode) {

    let parent = child.parent;
    let siblings = parent.children;
    let index = siblings.indexOf(child) + 1;
    return index;

}