// setConnectorColor generated by Figma Go Grafcet.Online Plugin
// https://www.figma.com/file/PMcaH6WLGpkdwvuEb709zg/setConnectorColor-%40Go-Plugin%2FFigjam-Utils?node-id=0%3A1

async function setConnectorColor(connector,
    CONNECTOR_COLOR={"r":0.7686274647712708,"g":0.7686274647712708,"b":0.7686274647712708},
    CONNECTOR_NO_DASH = []
    ) {

    let color = CONNECTOR_COLOR;
    let strokes = [{type: 'SOLID', color: color, visible: true}];
    try {

        connector.strokes = strokes;
        connector.dashPattern = CONNECTOR_NO_DASH;
    }
    catch(error) {
        _debug_alert(`[214. 2022/01/30 09:32:48]`);
    }
}