// Generated by figma Go Grafcet.Online Plugin
// https://www.figma.com/file/pHepd3Qj4grhp00UsvhC9w/sortConnectorsByLayer-%40Go-Plugin-Opensource%2FFigma-Utilities?node-id=2%3A2
async function sortConnectorsByLayer(connectors) {
    let sortedConnectorsByLayer = connectors.sort((A, B) => {
            let delta;
            let indexA = getChildIndex(A);
            let indexB = getChildIndex(B);
            delta = indexA - indexB;
            return delta;
    });
    return sortedConnectorsByLayer;
}